export const alertConstants = {

    ALERT_SUCCESS: 'ALERT_SUCCESS',
    ALERT_ERROR: 'ALERT_ERROR'
    
};

export const registerConstants = {

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE'

};

export const loginConstants = {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT'
};

export const allExpenseConstants = {
    FETCH_EXPENSE_REQUEST: 'FETCH_EXPENSE_REQUEST',
    FETCH_EXPENSE_SUCCESS: 'FETCH_EXPENSE_SUCCESS',
    FETCH_EXPENSE_FAILURE: 'FETCH_EXPENSE_FAILURE'
};