export const alertConstants = {

    ALERT_SUCCESS: 'ALERT_SUCCESS',
    ALERT_ERROR: 'ALERT_ERROR'
    
};

export const registerConstants = {

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    CHANGE_REGISTER_INPUT: 'CHANGE_REGISTER_INPUT'

};

export const loginConstants = {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    CHANGE_LOGIN_INPUT: 'CHANGE_LOGIN_INPUT',
    UPDATE_INITIAL_LOGIN_STATE: 'UPDATE_INITIAL_LOGIN_STATE',
    LOGOUT: 'LOGOUT'
};

export const allExpenseConstants = {
    FETCH_EXPENSE_REQUEST: 'FETCH_EXPENSE_REQUEST',
    FETCH_EXPENSE_SUCCESS: 'FETCH_EXPENSE_SUCCESS',
    FETCH_EXPENSE_FAILURE: 'FETCH_EXPENSE_FAILURE'
};

export const saveExpenseConstants = {
    SAVE_EXPENSE_REQUEST: 'SAVE_EXPENSE_REQUEST',
    SAVE_EXPENSE_SUCCESS: 'SAVE_EXPENSE_SUCCESS',
    SAVE_EXPENSE_FAILURE: 'SAVE_EXPENSE_FAILURE',
    CHANGE_EXPENSE_INPUT: 'CHANGE_EXPENSE_INPUT'
};